@extends('layouts.admin')

@section('title', 'Content manager | Velmora Admin')
@section('content')
<p class="eyebrow">Website content</p><h1 class="mt-2 font-display text-4xl text-forest">Content manager</h1>
<div class="mt-8 space-y-8">
    <section><h2 class="font-display text-2xl text-forest">Product divisions</h2><div class="mt-4 grid gap-4 xl:grid-cols-2">
        @foreach($divisions as $division)
            <form class="space-y-3 rounded-2xl border border-mist bg-white p-5" method="post" action="{{ route('admin.divisions.update',$division) }}" enctype="multipart/form-data">@csrf @method('PATCH')
                <div class="flex items-center justify-between gap-3"><h3 class="font-semibold">{{ $division->slug }}</h3><span class="text-xs text-stone">/{{ app()->getLocale() }}/divisions/{{ $division->slug }}</span></div>
                <div class="grid gap-3 sm:grid-cols-2"><label class="text-xs font-medium">Name (English)<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="name_en" value="{{ old('name_en',$division->localized('name','en')) }}" required></label><label class="text-xs font-medium">Name (Arabic)<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="name_ar" value="{{ old('name_ar',$division->localized('name','ar')) }}" dir="rtl"></label>
                <label class="text-xs font-medium">Summary (English)<textarea class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="summary_en" rows="2">{{ old('summary_en',$division->localized('summary','en')) }}</textarea></label><label class="text-xs font-medium">Summary (Arabic)<textarea class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="summary_ar" rows="2" dir="rtl">{{ old('summary_ar',$division->localized('summary','ar')) }}</textarea></label>
                <label class="text-xs font-medium sm:col-span-2">Description (English)<textarea class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="description_en" rows="2">{{ old('description_en',$division->localized('description','en')) }}</textarea></label><label class="text-xs font-medium sm:col-span-2">Description (Arabic)<textarea class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="description_ar" rows="2" dir="rtl">{{ old('description_ar',$division->localized('description','ar')) }}</textarea></label>
                <label class="text-xs font-medium">Sort order<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" type="number" min="0" name="sort_order" value="{{ $division->sort_order }}" required></label><label class="text-xs font-medium">Cover image (JPG/PNG/WebP)<input class="mt-1 w-full text-sm" type="file" name="cover_image" accept=".jpg,.jpeg,.png,.webp"></label></div>
                <label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($division->is_active)>Visible on website</label><button class="rounded-full bg-forest px-5 py-2 text-sm font-semibold text-white">Save division</button>
            </form>
        @endforeach
    </div></section>
    <section><h2 class="font-display text-2xl text-forest">Supply packages</h2><div class="mt-4 grid gap-4 xl:grid-cols-2">
        @foreach($packages as $package)
            <form class="space-y-3 rounded-2xl border border-mist bg-white p-5" method="post" action="{{ route('admin.supply-packages.update',$package) }}">@csrf @method('PATCH')
                <div class="flex items-center justify-between gap-3"><h3 class="font-semibold">{{ $package->slug }}</h3><span class="text-xs text-stone">{{ $package->localized('name','en') }}</span></div>
                <div class="grid gap-3 sm:grid-cols-2"><label class="text-xs font-medium">Name (English)<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="name_en" value="{{ old('name_en',$package->localized('name','en')) }}" required></label><label class="text-xs font-medium">Name (Arabic)<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="name_ar" value="{{ old('name_ar',$package->localized('name','ar')) }}" dir="rtl"></label>
                <label class="text-xs font-medium">Description (English)<textarea class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="description_en" rows="2">{{ old('description_en',$package->localized('description','en')) }}</textarea></label><label class="text-xs font-medium">Description (Arabic)<textarea class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="description_ar" rows="2" dir="rtl">{{ old('description_ar',$package->localized('description','ar')) }}</textarea></label>
                <label class="text-xs font-medium">Audience (English)<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="audience_en" value="{{ old('audience_en',$package->localized('audience','en')) }}"></label><label class="text-xs font-medium">Audience (Arabic)<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="audience_ar" value="{{ old('audience_ar',$package->localized('audience','ar')) }}" dir="rtl"></label>
                <label class="text-xs font-medium">Minimum quantity note (English)<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="min_qty_note_en" value="{{ old('min_qty_note_en',$package->localized('min_qty_note','en')) }}"></label><label class="text-xs font-medium">Minimum quantity note (Arabic)<input class="mt-1 w-full rounded-lg border border-mist px-3 py-2 text-sm" name="min_qty_note_ar" value="{{ old('min_qty_note_ar',$package->localized('min_qty_note','ar')) }}" dir="rtl"></label></div>
                <div class="flex flex-wrap items-center gap-4"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($package->is_active)>Visible</label><label class="text-xs">Sort<input class="ms-2 w-20 rounded border border-mist px-2 py-1" type="number" name="sort_order" value="{{ $package->sort_order }}" required></label><button class="rounded-full bg-forest px-5 py-2 text-sm font-semibold text-white">Save package</button></div>
            </form>
        @endforeach
    </div></section>
    <section class="grid gap-8 xl:grid-cols-2">
        <div class="rounded-2xl border border-mist bg-white p-6"><h2 class="font-display text-2xl text-forest">Packaging options</h2><ul class="mt-3 divide-y divide-mist">@forelse($packagingOptions as $option)<li class="flex justify-between py-2 text-sm"><span>{{ $option->localized('name') }}</span><span class="text-stone">{{ $option->kind }} @if($option->size_value)· {{ $option->size_value }} {{ $option->size_unit }}@endif</span></li>@empty<li class="py-3 text-sm text-stone">No packaging options yet.</li>@endforelse</ul>
            <form class="mt-5 space-y-3 border-t border-mist pt-5" method="post" action="{{ route('admin.packaging-options.store') }}">@csrf<h3 class="font-semibold">Add a packaging option</h3><div class="grid gap-3 sm:grid-cols-2"><input class="rounded-lg border border-mist px-3 py-2 text-sm" name="name_en" placeholder="Name (English)" required><input class="rounded-lg border border-mist px-3 py-2 text-sm" name="name_ar" placeholder="Name (Arabic)" dir="rtl"><select class="rounded-lg border border-mist px-3 py-2 text-sm" name="kind">@foreach(['bag','carton','jar','pallet','bulk','container','custom'] as $kind)<option value="{{ $kind }}">{{ ucfirst($kind) }}</option>@endforeach</select><input class="rounded-lg border border-mist px-3 py-2 text-sm" type="number" min="0" step="any" name="size_value" placeholder="Size (optional)"><input class="rounded-lg border border-mist px-3 py-2 text-sm" name="size_unit" placeholder="Unit, e.g. kg"></div><button class="rounded-full bg-forest px-5 py-2 text-sm font-semibold text-white">Add packaging</button></form>
        </div>
        <div class="rounded-2xl border border-mist bg-white p-6"><h2 class="font-display text-2xl text-forest">Catalog files</h2><div class="mt-3 space-y-3">@forelse($catalogs as $catalog)<form class="rounded-xl border border-mist p-3 text-sm" method="post" action="{{ route('admin.catalogs.update',$catalog) }}" enctype="multipart/form-data">@csrf @method('PATCH')<div class="grid gap-2 sm:grid-cols-2"><input class="rounded-lg border border-mist px-2 py-2" name="title_en" value="{{ $catalog->localized('title','en') }}" required><input class="rounded-lg border border-mist px-2 py-2" name="title_ar" value="{{ $catalog->localized('title','ar') }}" dir="rtl"><select class="rounded-lg border border-mist px-2 py-2" name="division_id"><option value="">Combined catalog</option>@foreach($divisions as $division)<option value="{{ $division->id }}" @selected($catalog->division_id===$division->id)>{{ $division->localized('name') }}</option>@endforeach</select><input class="rounded-lg border border-mist px-2 py-2" type="file" name="file" accept=".pdf"></div><div class="mt-2 flex flex-wrap items-center gap-4"><label class="flex items-center gap-2"><input type="checkbox" name="requires_email" value="1" @checked($catalog->requires_email)>Email gate</label><label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1" @checked($catalog->is_active)>Published</label><span class="text-xs text-stone">{{ $catalog->division?->localized('name') ?? 'Combined' }}</span><button class="rounded-full bg-forest px-4 py-2 text-xs font-semibold text-white">Save</button></div></form>@empty<p class="py-3 text-sm text-stone">No catalogs uploaded.</p>@endforelse</div>
            <form class="mt-5 space-y-3 border-t border-mist pt-5" method="post" action="{{ route('admin.catalogs.store') }}" enctype="multipart/form-data">@csrf<h3 class="font-semibold">Upload PDF catalog</h3><input class="w-full rounded-lg border border-mist p-2 text-sm" name="title_en" placeholder="Title (English)" required><input class="w-full rounded-lg border border-mist p-2 text-sm" name="title_ar" placeholder="Title (Arabic)" dir="rtl"><select class="w-full rounded-lg border border-mist p-2 text-sm" name="division_id"><option value="">Combined catalog</option>@foreach($divisions as $division)<option value="{{ $division->id }}">{{ $division->localized('name') }}</option>@endforeach</select><input class="w-full rounded-lg border border-mist p-2 text-sm" type="file" name="file" accept=".pdf" required><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="requires_email" value="1">Require email for download</label><button class="rounded-full bg-forest px-5 py-2 text-sm font-semibold text-white">Upload catalog</button></form>
        </div>
    </section>
</div>
@endsection
